#: import icon kivysome.icon


<IconButton>
    size_hint: 1, 1
    background_down: ''
    background_normal: ''
    background_color: [1, 1, 0, 0]
    text_size: self.size
    halign: 'center'
    valign: 'center'
    markup: True
    font_size: sp(20)
    color: app.theme_palette['text_background_color']


<RouteTitleLabel@Label>
    size_hint: 7, 1
    text_size: self.size
    halign: 'left'
    valign: 'center'
    font_size: sp(20)
    color: app.theme_palette['text_primary_color']